//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTUALWEBAPP.CoordinateAndCostLivingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoordinateAndCostLivingService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCostOfLiving", ReplyAction="http://tempuri.org/IService1/GetCostOfLivingResponse")]
        string[] GetCostOfLiving(string city, string state, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCostOfLiving", ReplyAction="http://tempuri.org/IService1/GetCostOfLivingResponse")]
        System.Threading.Tasks.Task<string[]> GetCostOfLivingAsync(string city, string state, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCoordinates", ReplyAction="http://tempuri.org/IService1/getCoordinatesResponse")]
        string[] getCoordinates(string city, string state, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCoordinates", ReplyAction="http://tempuri.org/IService1/getCoordinatesResponse")]
        System.Threading.Tasks.Task<string[]> getCoordinatesAsync(string city, string state, string country);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ACTUALWEBAPP.CoordinateAndCostLivingService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ACTUALWEBAPP.CoordinateAndCostLivingService.IService1>, ACTUALWEBAPP.CoordinateAndCostLivingService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetCostOfLiving(string city, string state, string country) {
            return base.Channel.GetCostOfLiving(city, state, country);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCostOfLivingAsync(string city, string state, string country) {
            return base.Channel.GetCostOfLivingAsync(city, state, country);
        }
        
        public string[] getCoordinates(string city, string state, string country) {
            return base.Channel.getCoordinates(city, state, country);
        }
        
        public System.Threading.Tasks.Task<string[]> getCoordinatesAsync(string city, string state, string country) {
            return base.Channel.getCoordinatesAsync(city, state, country);
        }
    }
}
