//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTUALWEBAPP.ForecastAndAlertService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ForecastAndAlertService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWeatherAlerts", ReplyAction="http://tempuri.org/IService1/getWeatherAlertsResponse")]
        string getWeatherAlerts(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getWeatherAlerts", ReplyAction="http://tempuri.org/IService1/getWeatherAlertsResponse")]
        System.Threading.Tasks.Task<string> getWeatherAlertsAsync(string state);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Weather5day", ReplyAction="http://tempuri.org/IService1/Weather5dayResponse")]
        string Weather5day(string in_zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Weather5day", ReplyAction="http://tempuri.org/IService1/Weather5dayResponse")]
        System.Threading.Tasks.Task<string> Weather5dayAsync(string in_zipcode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ACTUALWEBAPP.ForecastAndAlertService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ACTUALWEBAPP.ForecastAndAlertService.IService1>, ACTUALWEBAPP.ForecastAndAlertService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getWeatherAlerts(string state) {
            return base.Channel.getWeatherAlerts(state);
        }
        
        public System.Threading.Tasks.Task<string> getWeatherAlertsAsync(string state) {
            return base.Channel.getWeatherAlertsAsync(state);
        }
        
        public string Weather5day(string in_zipcode) {
            return base.Channel.Weather5day(in_zipcode);
        }
        
        public System.Threading.Tasks.Task<string> Weather5dayAsync(string in_zipcode) {
            return base.Channel.Weather5dayAsync(in_zipcode);
        }
    }
}
