//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTUALWEBAPP.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateSolarOutput", ReplyAction="http://tempuri.org/IService1/CalculateSolarOutputResponse")]
        double CalculateSolarOutput(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateSolarOutput", ReplyAction="http://tempuri.org/IService1/CalculateSolarOutputResponse")]
        System.Threading.Tasks.Task<double> CalculateSolarOutputAsync(double latitude, double longitude);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTotalCrimes", ReplyAction="http://tempuri.org/IService1/GetTotalCrimesResponse")]
        int GetTotalCrimes(string stateAbbreviation, int fromYear, int toYear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTotalCrimes", ReplyAction="http://tempuri.org/IService1/GetTotalCrimesResponse")]
        System.Threading.Tasks.Task<int> GetTotalCrimesAsync(string stateAbbreviation, int fromYear, int toYear);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ACTUALWEBAPP.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ACTUALWEBAPP.ServiceReference1.IService1>, ACTUALWEBAPP.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateSolarOutput(double latitude, double longitude) {
            return base.Channel.CalculateSolarOutput(latitude, longitude);
        }
        
        public System.Threading.Tasks.Task<double> CalculateSolarOutputAsync(double latitude, double longitude) {
            return base.Channel.CalculateSolarOutputAsync(latitude, longitude);
        }
        
        public int GetTotalCrimes(string stateAbbreviation, int fromYear, int toYear) {
            return base.Channel.GetTotalCrimes(stateAbbreviation, fromYear, toYear);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalCrimesAsync(string stateAbbreviation, int fromYear, int toYear) {
            return base.Channel.GetTotalCrimesAsync(stateAbbreviation, fromYear, toYear);
        }
    }
}
